language: python
python: 3.6
cache:
  - pip
  - ccache
sudo: required
dist: trusty

os:
  - linux
services:
  - redis-server
  - mongodb
env:
  - JOB=test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - git
      - python3
      - python3-numpy
      - python3-pip
      - ccache

install:
  - sudo pip3 install -r requirements.txt

before_install:

script:
  - if [[ "$JOB" == "test" ]]; then /bin/bash ./test.sh; fi

notifications:
  email:
    on_success: change
    on_failure: always
